name: lawad
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

######## fait le 20220911 ############
# Liens
url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
    
######## fait le 20220911 ############
# Audio
just_audio: ^0.9.20
  
    
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

######## fait le 20220911 ############
fonts:
    - family: Amazigh tms
      fonts:
        - asset: assets/fonts/MZTIMENR.TTF
    - family: Amazigh arial bold
      fonts:
        - asset: assets/fonts/MZARIALB.TTF
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
