// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuGfyNsLv8hrux-MW8xbh70Mdcd112MEU',
    appId: '1:1030936623079:web:256cdcc3d37ca6ebdfaf42',
    messagingSenderId: '1030936623079',
    projectId: 'alphabyle-d2c5b',
    authDomain: 'alphabyle-d2c5b.firebaseapp.com',
    storageBucket: 'alphabyle-d2c5b.appspot.com',
    measurementId: 'G-P6KX4C3X2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArnzwGh4x5FQ7ADLANu4qyMFn0JI4KhFc',
    appId: '1:1030936623079:android:a65a4877d841addfdfaf42',
    messagingSenderId: '1030936623079',
    projectId: 'alphabyle-d2c5b',
    storageBucket: 'alphabyle-d2c5b.appspot.com',
  );
}
